# Generated by Django 2.2.16 on 2022-05-27 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.TextField(default='', help_text='Введите текст поста', verbose_name='Текст поста'),
        ),
    ]
